### ISSUE TITLE
The project section is not responsive.

### ISSUE THREAD

**Issue by shradhaagarwal01** [shradhaagarwal01/portfolio#5]
The size of the pictures is not optimized in mobile view.

**Comment by FedeHerrera10** [comment]
I can contribute to this problem

**Comment by FedeHerrera10** [comment]
Hi!,I would like to contribute to your issue.

**Comment by shradhaagarwal01** [comment]
Hello, please go ahead :)

**Comment by FedeHerrera10** [comment]
> Hello, please go ahead :)

Sorry, could you assign me the issue again

**Comment by FedeHerrera10** [comment]
Sorry, could you assign me the issue again

**Comment by shradhaagarwal01** [comment]
Done!

**Comment by FedeHerrera10** [comment]
good I would like to do a pr would you give me permission to publish the brach

**Comment by FedeHerrera10** [comment]
Resolve issue.
